package io.github.kantis.mikrom.generator

import io.github.kantis.mikrom.MikromInternal
import io.github.kantis.mikrom.ParameterMapper

/**
 * An interface for a [io.github.kantis.mikrom.ParameterMapper] instance generated by the compiler plugin.
 *
 * Should not be implemented manually or used directly.
 */
@MikromInternal
public interface GeneratedParameterMapper<in T> : ParameterMapper<T>
