

package io.github.kantis.mikrom.plugin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.kantis.mikrom.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("BothMapped.kt")
  public void testBothMapped() {
    runTest("testData/box/BothMapped.kt");
  }

  @Test
  @TestMetadata("ColumnAnnotation.kt")
  public void testColumnAnnotation() {
    runTest("testData/box/ColumnAnnotation.kt");
  }

  @Test
  @TestMetadata("NamingStrategy.kt")
  public void testNamingStrategy() {
    runTest("testData/box/NamingStrategy.kt");
  }

  @Test
  @TestMetadata("NullableValueClass.kt")
  public void testNullableValueClass() {
    runTest("testData/box/NullableValueClass.kt");
  }

  @Test
  @TestMetadata("ParameterMapped.kt")
  public void testParameterMapped() {
    runTest("testData/box/ParameterMapped.kt");
  }

  @Test
  @TestMetadata("Person.kt")
  public void testPerson() {
    runTest("testData/box/Person.kt");
  }

  @Test
  @TestMetadata("ValueClass.kt")
  public void testValueClass() {
    runTest("testData/box/ValueClass.kt");
  }
}
